version: '3.7'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - '5432:5432'

  adminer:
    container_name: db-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
